apiVersion: v1
kind: Service
metadata:
  name: inventory
  labels:
    app: inventory
spec:
  ports:
    - port: 8080
      name: http
      targetPort: 8080
  selector:
    app: inventory

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-v1
  labels:
    app: inventory
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
      version: v1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: inventory
        version: v1
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: inventory
          image: solarmesh/solar-mock-app:latest
          imagePullPolicy: Always # IfNotPresent
          env:
            - name: APP_NAME
              value: inventory
            - name: APP_VERSION
              value: v1
            - name: CLUSTER_NAME
              value: cluster01
            - name: USER_DATA
              value: Inventory v1
            - name: UPSTREAM_URLS
              value: http://product:8080/,
          ports:
            - containerPort: 8080  