apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
    - port: 8080
      name: http
      targetPort: 8080
  selector:
    app: mysql

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-v1
  labels:
    app: mysql
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      version: v1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: mysql
        version: v1
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: mysql
          image: solarmesh/mockservices:latest
          imagePullPolicy: Always # IfNotPresent
          env:
            - name: APP_NAME
              value: mysql
            - name: APP_VERSION
              value: v8.0
            - name: CLUSTER_NAME
              value: cluster01
            - name: USER_DATA
              value: mysql
            - name: TCP_SERVER_ENABLED
              value: true
            - name: TCP_SERVER_PORT
              value: 3306
          ports:
            - containerPort: 8080  