apiVersion: v1
kind: Service
metadata:
  name: order
  labels:
    app: order
spec:
  ports:
    - port: 8080
      name: http
      targetPort: 8080
  selector:
    app: order

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-v1
  labels:
    app: order
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
      version: v1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: order
        version: v1
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: order
          image: solarmesh/mockservices:latest
          imagePullPolicy: Always # IfNotPresent
          env:
            - name: APP_PROFILES_ACTIVE
              value: dev
            - name: APP_NAME
              value: order
            - name: APP_VERSION
              value: v1
            - name: CLUSTER_NAME
              value: cluster01
            - name: USER_DATA
              value: The order app v1
            - name: UPSTREAM_URLS
              value: http://payment:8080/,grpc://product:7575,grpc://inventory:7575,http://user:8080,
          ports:
            - containerPort: 8080  