apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    app: payment
spec:
  ports:
    - port: 8080
      name: http
      targetPort: 8080
  selector:
    app: payment

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-v1
  labels:
    app: payment
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
      version: v1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: payment
        version: v1
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: payment
          image: solarmesh/solar-mock-app:latest
          imagePullPolicy: Always # IfNotPresent
          env:
            - name: APP_NAME
              value: payment
            - name: APP_VERSION
              value: v1
            - name: CLUSTER_NAME
              value: cluster01
            - name: USER_DATA
              value: Your customized user data
            - name: UPSTREAM_URLS
              value: http://user:8080/,
          ports:
            - containerPort: 8080  