apiVersion: v1
kind: Service
metadata:
  name: recommendation
  labels:
    app: recommendation
spec:
  ports:
    - port: 8080
      name: http
      targetPort: 8080
  selector:
    app: recommendation

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-v1
  labels:
    app: recommendation
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation
      version: v1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: recommendation
        version: v1
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: recommendation
          image: solarmesh/mockservices:latest
          imagePullPolicy: Always # IfNotPresent
          env:
            - name: APP_PROFILES_ACTIVE
              value: dev
            - name: APP_NAME
              value: recommendation
            - name: APP_VERSION
              value: v1
            - name: CLUSTER_NAME
              value: cluster01
            - name: USER_DATA
              value: Your customized user data
            - name: UPSTREAM_URLS
              value: http://user:8080,
          ports:
            - containerPort: 8080  