apiVersion: v1
kind: Service
metadata:
  name: reviews
  labels:
    app: reviews
spec:
  ports:
    - port: 8080
      name: http
      targetPort: 8080
  selector:
    app: reviews

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v1
  labels:
    app: reviews
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
      version: v1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: reviews
        version: v1
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: reviews
          image: solarmesh/mockservices:latest
          imagePullPolicy: Always # IfNotPresent
          env:
            - name: APP_PROFILES_ACTIVE
              value: dev
            - name: APP_NAME
              value: reviews
            - name: APP_VERSION
              value: v1
            - name: CLUSTER_NAME
              value: cluster01
            - name: USER_DATA
              value: The reviews app v1
            - name: UPSTREAM_URLS
              value: http://user:8080,
          ports:
            - containerPort: 8080  