# config file for testing

server:
  port: 8081

logging:
  level: debug

grpc:
  server:
    port: 7576

tcp:
  server:
    enabled: false
    port: 8586

jaeger:
  config:
    reporter:
      localAgentHostPort: localhost:6831 # you should change to your own jaeger server if you wish to debug in your local machine