# config file for testing

server:
  port: 9090

logging:
  level: debug

grpc:
  server:
    port: 7070

tcp:
  server:
    enabled: true
    port: 8383

jaeger:
  config:
    reporter:
      localAgentHostPort: localhost:6831 # you should change to your own jaeger server if you wish to debug in your local machine