# config file for testing

server:
  port: 8080

logging:
  level: debug

grpc:
  server:
    port: 7575

tcp:
  server:
    enabled: true
    port: 8585

jaeger:
  config:
    reporter:
      localAgentHostPort: localhost:6831 # you should change to your own jaeger server if you wish to debug in your local machine