# config file for testing
# filename should be application.yml

app:
  project: solarmesh
  name: mockservices

logging:
  level: info

grpc:
  server:
    enabled: true
    network: tcp
    port: 7575

tcp:
  server:
    enabled: true
    port: 8585

jaeger:
  config:
    sampler:
      type: const
      param: 1
    reporter:
      logSpans: true
      localAgentHostPort: jaeger-agent.istio-system:6831
      bufferFlushInterval: 1000000
