# config file for testing
# filename should be application.yml

app:
  project: solarmesh
  name: mockservices
  profiles:
    include:
    - logging
    - locale
    - grpc
    - tcp
    - jaeger
    - httpclient
    - actuator

logging:
  level: info

grpc:
  server:
    enabled: true
    network: tcp
    port: 7575

tcp:
  server:
    enabled: false
    port: 8586

jaeger:
  config:
    serviceName: ${app.name}
    sampler:
      type: const
      param: 1
    reporter:
      logSpans: true
      localAgentHostPort: jaeger-agent.istio-system:6831
      bufferFlushInterval: 1000000
